Pipeline updates for ibmint
Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

diff --git a/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml b/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
--- a/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
+++ b/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
@@ -45,40 +45,54 @@ spec:
       volumeMounts:
         - mountPath: /work
           name: work
-    - name: maven-build
-      image: $(params.dockerRegistry)/$(params.buildImage)
+    - name: ibmint-build
+      #image: $(params.dockerRegistry)/$(params.buildImage)
+      image: cp.icr.io/cp/appc/ace:12.0.11.0-r1
       #
       # Runs the build and unit test phases, leaving the results in the work directory
       # for later steps.
       #
       script: |
         #!/bin/bash
+        set -e # Fail on error
         export LICENSE=accept
         . /opt/ibm/ace-12/server/bin/mqsiprofile
-        export PATH=/opt/ibm/ace-12/common/jdk/bin:$PATH
-        which javac
-        javac -version
-        mkdir /work/maven-output
+        
         cd /work/ace-demo-pipeline
-        mvn --no-transfer-progress -Dinstall.work.directory=/work/maven-output/ace-server install
+        mkdir /work/ibmint-output
+        mqsicreateworkdir /work/ibmint-output/ace-server
+        # Using --compile-maps-and-schemas for 12.0.11 and later . . . 
+        ibmint deploy --input-path . --output-work-directory /work/ibmint-output/ace-server --project TeaSharedLibraryJava --project TeaSharedLibrary --project TeaRESTApplication --compile-maps-and-schemas 
+        ibmint optimize server --work-dir /work/ibmint-output/ace-server
+
+        # Copy the contents of the work directory into a new unit-test-specific work directory
+        # This avoids the risk of unit tests files being deployed in the real containers, and
+        # is quicker than building the application again
+        mqsicreateworkdir /work/ut-work-dir
+        (cd /work/ibmint-output/ace-server && tar -cf - * ) | (cd /work/ut-work-dir && tar -xf - )
+        # Build just the unit tests
+        ibmint deploy --input-path . --output-work-directory /work/ut-work-dir --project TeaRESTApplication_UnitTest
+
+        # Run the unit tests
+        IntegrationServer -w /work/ut-work-dir --no-nodejs --start-msgflows false --test-project TeaRESTApplication_UnitTest
       volumeMounts:
         - mountPath: /work
           name: work
     - name: container-setup
       image: $(params.dockerRegistry)/$(params.buildImage)
       #
-      # Copies files around and changes permissions to allow Kaniko to build the actual
-      # runtime image in the next step. Also copies the Dockerfile into place for Kaniko.
+      # Copies files around and changes permissions to allow Kaniko/buildah to build the actual
+      # runtime image in the next step. Also copies the Dockerfile into place for Kaniko/buildah.
       #
       script: |
         #!/bin/bash
-        cd /work/maven-output
+        cd /work/ibmint-output
         cp /work/ace-demo-pipeline/tekton/os/cp4i/Dockerfile Dockerfile
         # Fix permissions issues 
-        chmod 777 /work/maven-output /work/maven-output/Dockerfile
-        chmod -R a+r /work/maven-output
-        find /work/maven-output -type d -print | xargs chmod 775
-        ls -l /work/maven-output
+        chmod 777 /work/ibmint-output /work/ibmint-output/Dockerfile
+        chmod -R a+r /work/ibmint-output
+        find /work/ibmint-output -type d -print | xargs chmod 775
+        ls -l /work/ibmint-output
       volumeMounts:
         - mountPath: /work
           name: work
@@ -88,7 +102,7 @@ spec:
       securityContext:
         runAsUser: 0
         # Needed for hostPath volumes on OpenShift
-        #privileged: true
+        privileged: true
         capabilities:
           add: ["CHOWN", "DAC_OVERRIDE","FOWNER","SETFCAP","SETGID","SETUID"]
       # specifying DOCKER_CONFIG is required to allow buildah to detect docker credential
@@ -99,7 +113,7 @@ spec:
         date
         buildah --storage-driver=overlay bud --format=oci --tls-verify=false --no-cache \
           --build-arg BASE_IMAGE=$(params.dockerRegistry)/$(params.runtimeImage) \
-          -f /work/maven-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i /work/maven-output
+          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i /work/ibmint-output
         date
         buildah  --storage-driver=overlay push --tls-verify=false --digestfile /tmp/image-digest \
           $(params.dockerRegistry)/tea-tekton-cp4i  "docker://$(params.dockerRegistry)/tea-tekton-cp4i"
@@ -111,7 +125,7 @@ spec:
         - name: varlibcontainers
           mountPath: /var/lib/containers
     - name: component-test
-      image: $(params.dockerRegistry)/$(params.buildImage)
+      image: cp.icr.io/cp/appc/ace:12.0.11.0-r1
       #
       # Builds and runs the component tests using the JDBC credentials provided from
       # the secret. Also uses the same init-creds.sh script used by the non-CP4i image
@@ -122,20 +136,28 @@ spec:
       #
       script: |
         #!/bin/bash
+        set -e # Fail on error
         export LICENSE=accept
         . /opt/ibm/ace-12/server/bin/mqsiprofile
         export PATH=/opt/ibm/ace-12/common/jdk/bin:$PATH
         # Slightly hacky, but quicker than building everything again!
-        (cd /work/maven-output/ace-server/run && tar -cf - * ) | (cd /home/aceuser/ace-server/run && tar -xf - )
+        (cd /work/ibmint-output/ace-server && tar -cf - * ) | (cd /home/aceuser/ace-server && tar -xf - )
         ls -l /home/aceuser/ace-server
         # Set up credentials for the component tests; init-creds.sh looks in /tmp for policy
         cp /work/ace-demo-pipeline/demo-infrastructure/TEAJDBC.policyxml /tmp/
         bash /work/ace-demo-pipeline/demo-infrastructure/init-creds.sh
         # Build and run the tests
-        cd /work/ace-demo-pipeline/TeaRESTApplication_ComponentTest
-        mvn --no-transfer-progress -Dct.work.directory=/home/aceuser/ace-server verify
-        # Slightly hacky, but quicker than building everything again!
-        (cd /home/aceuser/ace-server/run && tar -cf - * ) | (cd /work/maven-output/ace-server/run && tar -xf - )
+        cd /work/ace-demo-pipeline
+
+        # Build just the component tests
+        ibmint deploy --input-path . --output-work-directory /home/aceuser/ace-server --project TeaRESTApplication_ComponentTest
+
+        # Run the component tests
+        IntegrationServer -w /home/aceuser/ace-server --no-nodejs --start-msgflows false --test-project TeaRESTApplication_ComponentTest
+
+        # Quicker than building everything again - we just copy the component test work directory 
+        # into the correct location for the container build in the next step
+        (cd /home/aceuser/ace-server && tar -cf - * ) | (cd /work/ibmint-output/ace-server && tar -xf - )
       volumeMounts:
         - mountPath: /work
           name: work
@@ -149,13 +171,13 @@ spec:
       #
       script: |
         #!/bin/bash
-        cd /work/maven-output
+        cd /work/ibmint-output
         cp /work/ace-demo-pipeline/tekton/os/cp4i/Dockerfile Dockerfile
         # Fix permissions issues 
-        chmod 777 /work/maven-output /work/maven-output/Dockerfile
-        chmod -R a+r /work/maven-output
-        find /work/maven-output -type d -print | xargs chmod 775
-        ls -l /work/maven-output/ace-server/run
+        chmod 777 /work/ibmint-output /work/ibmint-output/Dockerfile
+        chmod -R a+r /work/ibmint-output
+        find /work/ibmint-output -type d -print | xargs chmod 775
+        ls -l /work/ibmint-output/ace-server/run
       volumeMounts:
         - mountPath: /work
           name: work
@@ -165,7 +187,7 @@ spec:
       securityContext:
         runAsUser: 0
         # Needed for hostPath volumes on OpenShift
-        #privileged: true
+        privileged: true
         capabilities:
           add: ["CHOWN", "DAC_OVERRIDE","FOWNER","SETFCAP","SETGID","SETUID"]
       # specifying DOCKER_CONFIG is required to allow buildah to detect docker credential
@@ -176,7 +198,7 @@ spec:
         date
         buildah --storage-driver=overlay bud --format=oci --tls-verify=false --no-cache \
           --build-arg BASE_IMAGE=$(params.dockerRegistry)/tea-tekton-cp4i \
-          -f /work/maven-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i-ct /work/maven-output
+          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i-ct /work/ibmint-output
         date
         buildah  --storage-driver=overlay push --tls-verify=false --digestfile /tmp/image-digest \
           $(params.dockerRegistry)/tea-tekton-cp4i-ct  "docker://$(params.dockerRegistry)/tea-tekton-cp4i-ct"
@@ -226,6 +248,14 @@ spec:
     #
     #    time="2024-02-15T00:55:11Z" level=error msg="'overlay' is not supported over nfs at \"/var/lib/containers/storage/overlay\""
     # 
+    # or possibly failing with
+    #
+    # time="2024-02-15T20:05:58Z" level=warning msg="Network file system detected as backing store. Enforcing overlay option `force_mask=\"700\"`. Add it to storage.conf to silence this warning"
+    # Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied
+    # time="2024-02-15T20:05:58Z" level=warning msg="Network file system detected as backing store. Enforcing overlay option `force_mask=\"700\"`. Add it to storage.conf to silence this warning"
+    # time="2024-02-15T20:05:58Z" level=warning msg="failed to shutdown storage: \"mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied\""
+    #
+    # if not running privileged
     #- name: varlibcontainers
     #  persistentVolumeClaim:
     #    claimName: buildah-cache-nfs
