Add container tage from git commit id
Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

diff --git a/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml b/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
--- a/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
+++ b/tekton/os/cp4i/12-ibmint-cp4i-build-task.yaml
@@ -32,6 +32,13 @@ spec:
       type: string
     - name: runtimeImage
       type: string
+  results:
+    - name: tag
+      description: image tag of the form 20240220135127-6fe9106
+    - name: sha
+      description: container image hash for the application container
+    - name: ctsha
+      description: container image hash for the component test container
   steps:
     - name: clone
       image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
@@ -40,8 +47,15 @@ spec:
       # 
       script: |
         #!/bin/sh
+        set -e # Fail on error
         cd /work
         git clone -b $(params.revision) $(params.url)
+        cd ace-demo-pipeline
+        export DATE=$(date '+%Y%m%d%H%M%S')
+        export COMMIT=$(git log -1 --pretty=%h)
+        export TAG="$DATE"-"$COMMIT"
+        echo Setting container tag to "$TAG"
+        echo -n "$TAG" > $(results.tag.path)
       volumeMounts:
         - mountPath: /work
           name: work
@@ -98,7 +112,7 @@ spec:
           name: work
     - name: docker-build-and-push
       #image: quay.io/buildah/stable:v1
-      image: registry.redhat.io/rhel8/buildah
+      image: registry.redhat.io/rhel8/buildah:8.9-5
       securityContext:
         runAsUser: 0
         # Needed for hostPath volumes on OpenShift
@@ -111,14 +125,20 @@ spec:
           value: "/tekton/home/.docker/"
       script: |
         date
+        export TAG=`cat $(results.tag.path)`
+        echo Using $TAG as image tag
         buildah --storage-driver=overlay bud --format=oci --tls-verify=false --no-cache \
           --build-arg BASE_IMAGE=$(params.dockerRegistry)/$(params.runtimeImage) \
-          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i /work/ibmint-output
+          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i:$TAG /work/ibmint-output
         date
         buildah  --storage-driver=overlay push --tls-verify=false --digestfile /tmp/image-digest \
-          $(params.dockerRegistry)/tea-tekton-cp4i  "docker://$(params.dockerRegistry)/tea-tekton-cp4i"
-        printf '%s' "$(params.dockerRegistry)/tea-tekton-cp4i"
+          $(params.dockerRegistry)/tea-tekton-cp4i  "docker://$(params.dockerRegistry)/tea-tekton-cp4i:$TAG"
+        #printf '%s' "$(params.dockerRegistry)/tea-tekton-cp4i"
+        echo image digest:
+        cat /tmp/image-digest && echo
+        cat /tmp/image-digest >> $(results.sha.path)
         date
+
       volumeMounts:
         - mountPath: /work
           name: work
@@ -183,7 +203,7 @@ spec:
           name: work
     - name: docker-build-and-push-ct
       #image: quay.io/buildah/stable:v1
-      image: registry.redhat.io/rhel8/buildah
+      image: registry.redhat.io/rhel8/buildah:8.9-5
       securityContext:
         runAsUser: 0
         # Needed for hostPath volumes on OpenShift
@@ -196,14 +216,18 @@ spec:
           value: "/tekton/home/.docker/"
       script: |
         date
+        export TAG=`cat $(results.tag.path)`
+        echo Using $TAG as image tag
         buildah --storage-driver=overlay bud --format=oci --tls-verify=false --no-cache \
           --build-arg BASE_IMAGE=$(params.dockerRegistry)/tea-tekton-cp4i \
-          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i-ct /work/ibmint-output
+          -f /work/ibmint-output/Dockerfile -t $(params.dockerRegistry)/tea-tekton-cp4i-ct:$TAG /work/ibmint-output
         date
         buildah  --storage-driver=overlay push --tls-verify=false --digestfile /tmp/image-digest \
-          $(params.dockerRegistry)/tea-tekton-cp4i-ct  "docker://$(params.dockerRegistry)/tea-tekton-cp4i-ct"
+          $(params.dockerRegistry)/tea-tekton-cp4i-ct  "docker://$(params.dockerRegistry)/tea-tekton-cp4i-ct:$TAG"
+        echo image digest:
+        cat /tmp/image-digest && echo
+        cat /tmp/image-digest >> $(results.ctsha.path)
         date
-        printf '%s' "$(params.dockerRegistry)/tea-tekton-cp4i-ct"
       volumeMounts:
         - mountPath: /work
           name: work
@@ -218,8 +242,8 @@ spec:
     # 
     # Default buildah approach using emptyDir; takes about 2 minutes on a test SNO cluster
     # 
-    - name: varlibcontainers
-      emptyDir: {}
+    #- name: varlibcontainers
+    #  emptyDir: {}
     # 
     # Local directory for this pipeline; takes a few seconds after initial pull
     # 
@@ -237,9 +261,9 @@ spec:
     # 
     # Local disk using LVM operator on SNO; same speed as hostPath
     # 
-    #- name: varlibcontainers
-    #  persistentVolumeClaim:
-    #    claimName: buildah-cache
+    - name: varlibcontainers
+      persistentVolumeClaim:
+        claimName: buildah-cache
     # 
     # NFS mount from same subnet; initial pull took 35 minutes, and
     # subsequent builds took around 9 minutes.
