Aceaas and minikube updates (#51)
* Update ACEaaS pipeline picture

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Fix naming and add comments

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Update picture with new names

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Containers update

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Switch containers

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Libpath fix

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Change default image

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Add container version comments

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Backslash comments

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Tekton name generation

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Tekton dashboard

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Fix image link

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Update pipelines diagram

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Fix wording and diagrams

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Picture changes

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Minikube and CP4i updates

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Fix link

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Update pipeline

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Minikube fixes and doc updates

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Add links

* Update docs

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Doc and version fixup

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

* Remove extraneous typescript file

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

---------

Signed-off-by: Trevor Dolby <trevor.dolby@ibm.com>

diff --git a/demo-infrastructure/Jenkinsfile.aceaas b/demo-infrastructure/Jenkinsfile.aceaas
--- a/demo-infrastructure/Jenkinsfile.aceaas
+++ b/demo-infrastructure/Jenkinsfile.aceaas
@@ -1,7 +1,8 @@
 pipeline {
   agent { docker { 
+    /* See README-jenkins.md for image discussion */
     image 'cp.icr.io/cp/appc/ace:12.0.11.0-r1'
-    /* image 'ace-minimal:12.0.11.0-alpine' */
+    /* image 'ace-minimal-build:12.0.11.0-alpine' */
     args '-e LICENSE=accept --entrypoint ""'
   } }
   parameters {
@@ -12,6 +13,7 @@ pipeline {
     string(name: 'serverName',   defaultValue: '19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud', description: 'JDBC database host')
     string(name: 'portNumber',   defaultValue: '30699', description: 'JDBC database port')
     string(name: 'deployPrefix',   defaultValue: 'tdolby', description: 'ACEaaS artifact prefix')
+    /* Could put the endpoint in as a credential, but it's not really secret . . . */
     string(name: 'APPCON_ENDPOINT',   defaultValue: 'api.p-vir-c1.appconnect.automation.ibm.com', description: 'ACEaaS endpoint hostname')
     booleanParam(name: 'DEPLOY_CONFIGURATION', defaultValue: false, description: 'Create policies, runtime, etc')
   }
@@ -107,7 +109,7 @@ pipeline {
       }
     }
 
-    stage('Next stage deploy') {
+    stage('Push BAR file') {
       steps {
         sh "echo ${params.APPCON_ENDPOINT} > /tmp/APPCON_ENDPOINT"
         sh "echo ${params.deployPrefix} > /tmp/deployPrefix"
@@ -116,9 +118,9 @@ pipeline {
             # Set HOME to somewhere writable by Maven
             export HOME=/tmp
 
-            export LICENSE=accept
-            . /opt/ibm/ace-12/server/bin/mqsiprofile
-        
+            # Fix for ace-minimal-build and curl
+            unset LD_LIBRARY_PATH
+       
             set -e # Fail on error - this must be done after the profile in case the container has the profile loaded already
 
             echo "########################################################################"
@@ -135,6 +137,10 @@ pipeline {
               --data "{\\"apiKey\\": \\"${APPCON_API_KEY}\\"}" --output /tmp/token-output.txt
             cat /tmp/token-output.txt  | tr -d '{}"' | tr ',' '\n' | grep access_token | sed 's/access_token://g' > /tmp/APPCON_TOKEN
 
+            echo "########################################################################"
+            echo "# PUTting BAR file to ACE service"
+            echo "########################################################################" && echo
+
             curl -X PUT https://`cat /tmp/APPCON_ENDPOINT`/api/v1/bar-files/`cat /tmp/deployPrefix`-tea-jenkins \
               -H "x-ibm-instance-id: ${APPCON_INSTANCE_ID}" -H "Content-Type: application/octet-stream" \
               -H "Accept: application/json" -H "X-IBM-Client-Id: ${APPCON_CLIENT_ID}" -H "authorization: Bearer `cat /tmp/APPCON_TOKEN`" \
@@ -150,7 +156,7 @@ pipeline {
       }
     }
 
-    stage('Create configuration') {
+    stage('Create Configurations and IR') {
       when {
         expression {
           return params.DEPLOY_CONFIGURATION
@@ -168,7 +174,7 @@ pipeline {
             export LICENSE=accept
             . /opt/ibm/ace-12/server/bin/mqsiprofile
         
-            #set -e # Fail on error - this must be done after the profile in case the container has the profile loaded already
+            set -e # Fail on error - this must be done after the profile in case the container has the profile loaded already
 
             echo ========================================================================
             echo Creating `cat /tmp/deployPrefix`-jdbc-policies configuration
@@ -181,10 +187,14 @@ pipeline {
             (cd /tmp && /opt/ibm/ace-12/common/jdk/bin/jar cvf /tmp/JDBCPolicies.zip JDBCPolicies)
             cat /tmp/JDBCPolicies.zip | base64 -w 0 > /tmp/JDBCPolicies.zip.base64
             
+            # Fix for ace-minimal-build and curl
+            unset LD_LIBRARY_PATH
+
             cp tekton/aceaas/create-configuration-template.json /tmp/jdbc-policies-configuration.json
             sed -i "s/TEMPLATE_NAME/`cat /tmp/deployPrefix`-jdbc-policies/g" /tmp/jdbc-policies-configuration.json
             sed -i "s/TEMPLATE_TYPE/policyproject/g" /tmp/jdbc-policies-configuration.json
             sed -i "s/TEMPLATE_DESCRIPTION/`cat /tmp/deployPrefix` JDBCPolicies project/g" /tmp/jdbc-policies-configuration.json
+            # Backslash issues with groovy scripting - the effect is to escape / characters in the base64 data to avoid issues with sed
             sed -i "s/TEMPLATE_BASE64DATA/`cat /tmp/JDBCPolicies.zip.base64 | sed 's/\\//\\\\\\\\\\\\//g'`/g" /tmp/jdbc-policies-configuration.json
             #cat /tmp/jdbc-policies-configuration.json
 
@@ -202,6 +212,7 @@ pipeline {
             sed -i "s/TEMPLATE_NAME/`cat /tmp/deployPrefix`-jdbc-setdbparms/g" /tmp/jdbc-setdbparms-configuration.json
             sed -i "s/TEMPLATE_TYPE/setdbparms/g" /tmp/jdbc-setdbparms-configuration.json
             sed -i "s/TEMPLATE_DESCRIPTION/`cat /tmp/deployPrefix` JDBC credentials/g" /tmp/jdbc-setdbparms-configuration.json
+            # Backslash issues with groovy scripting - the effect is to escape / characters in the base64 data to avoid issues with sed
             sed -i "s/TEMPLATE_BASE64DATA/`cat /tmp/jdbc-setdbparms.base64 | sed 's/\\//\\\\\\\\\\\\//g'`/g" /tmp/jdbc-setdbparms-configuration.json
             #cat /tmp/jdbc-setdbparms-configuration.json
 
@@ -219,6 +230,7 @@ pipeline {
             sed -i "s/TEMPLATE_NAME/`cat /tmp/deployPrefix`-default-policy-project/g" /tmp/default-policy-project-configuration.json
             sed -i "s/TEMPLATE_TYPE/serverconf/g" /tmp/default-policy-project-configuration.json
             sed -i "s/TEMPLATE_DESCRIPTION/`cat /tmp/deployPrefix` default policy project for JDBC/g" /tmp/default-policy-project-configuration.json
+            # Backslash issues with groovy scripting - the effect is to escape / characters in the base64 data to avoid issues with sed
             sed -i "s/TEMPLATE_BASE64DATA/`cat /tmp/default-policy-project.base64 | sed 's/\\//\\\\\\\\\\\\//g'`/g" /tmp/default-policy-project-configuration.json
             #cat /tmp/default-policy-project-configuration.json
 
@@ -228,10 +240,11 @@ pipeline {
               --data-binary @/tmp/default-policy-project-configuration.json
 
             echo ========================================================================
-            echo Creating IR JSON
+            echo Creating IntegrationRuntime JSON
             echo ========================================================================
             cp tekton/aceaas/create-integrationruntime-template.json /tmp/create-integrationruntime.json
             sed -i "s/TEMPLATE_NAME/`cat /tmp/deployPrefix`-tea-jenkins-ir/g" /tmp/create-integrationruntime.json
+            # Backslash issues with groovy scripting - the effect is to escape / characters in the base64 data to avoid issues with sed
             sed -i "s/TEMPLATE_BARURL/`cat /tmp/BARURL | sed 's/\\//\\\\\\\\\\\\//g'`/g" /tmp/create-integrationruntime.json
             sed -i "s/TEMPLATE_POLICYPROJECT/`cat /tmp/deployPrefix`-jdbc-policies/g" /tmp/create-integrationruntime.json
             sed -i "s/TEMPLATE_SERVERCONF/`cat /tmp/deployPrefix`-default-policy-project/g" /tmp/create-integrationruntime.json
@@ -254,5 +267,7 @@ pipeline {
     APPCON_CLIENT_ID = credentials('APPCON_CLIENT_ID')
     APPCON_CLIENT_SECRET = credentials('APPCON_CLIENT_SECRET')
     APPCON_API_KEY = credentials('APPCON_API_KEY')
+    /* Could put the endpoint in as a credential, but it's not really secret . . . */
+    /* APPCON_ENDPOINT = credentials('APPCON_ENDPOINT') */
   }
 }
